const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home'
    },
    {
        title:'UI',
        key:'/ui',
        icon:'underline',
        children:[
            {
                title:'按钮',
                key:'/ui/buttons',
                icon:'bold',
            },
            {
                title:'弹框',
                key:'/ui/modals',
                icon:'stock',
            },
            {
                title:'Loading',
                key:'/ui/loadings',
                icon:'loading',
            },
            {
                title:'通知提醒',
                key:'/ui/notification',
                icon:'aliwangwang',
            },
            {
                title:'全局Message',
                key:'/ui/messages',
                icon:'message',
            },
            {
                title:'Tab页签',
                key:'/ui/tabs',
                icon:'wallet',
            },
            {
                title:'图片画廊',
                key:'/ui/gallery',
                icon:'picture',
            },
            {
                title:'轮播图',
                key:'/ui/carousel',
                icon:'video-camera',
            }
        ]
    },
    {
        title:'表单',
        key:'/form',
        icon:'table',
        children:[
            {
                title:'登录',
                key:'/form/login',
                icon:'user',
            },
            {
                title:'注册',
                key:'/form/reg',
                icon:'user-add',
            }
        ]
    },
    {
        title:'表格',
        key:'/table',
        icon:'profile',
        children:[
            {
                title:'基础表格',
                key:'/table/basic',
                icon:'pic-center',
            },
            {
                title:'高级表格',
                key:'/table/high',
                icon:'pic-left',
            }
        ]
    },
    {
        title:'富文本',
        key:'/rich',
        icon:'file',
    },
    {
        title:'城市管理',
        key:'/city',
        icon:'global',
    },
    {
        title:'订单管理',
        key:'/order',
        icon:'red-envelope',
        btnList:[
            {
                title:'订单详情',
                key:'/detail',
                icon:'layout',
            },
            {
                title:'结束订单',
                key:'/finish',
                icon:'poweroff',
            }
        ]
    },
    {
        title:'员工管理',
        key:'/user',
        icon:'robot',
    },
    {
        title:'车辆地图',
        key:'/bikeMap',
        icon:'car',
    },
    {
        title:'图标',
        key:'/charts',
        icon:'fund',
        children:[
            {
                title:'柱形图',
                key:'/charts/bar',
                icon:'bar-chart',
            },
            {
                title:'饼图',
                key:'/charts/pie',
                icon:'pie-chart',
            },
            {
                title:'折线图',
                key:'/charts/line',
                icon:'line-chart',
            },
        ]
    },
    {
        title:'权限设置',
        key:'/permission',
        icon:'setting',
    },
];
export default menuList;